name: micro_app_login
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none 

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  micro_core:
    path: ../../micro_core
  micro_shared:
    path: ../../micro_shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: