name: micro_core
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none 

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  micro_app_login:
    path: ../microapps/micro_app_login

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
